export const vuelos = [
  {
    "compania":"American Airlines",
    "hora":"06:01",
    "destino":"Gran Canaria",
    "duracion":77
  },
  {
    "compania":"Air France",
    "hora":"10:42",
    "destino":"Copenhague",
    "duracion":534
  },
  {
    "compania":"Swiss",
    "hora":"07:21",
    "destino":"Sevilla",
    "duracion":427
  },
  {
    "compania":"Ryanair",
    "hora":"13:53",
    "destino":"Copenhague",
    "duracion":583
  },
  {
    "compania":"Alitalia",
    "hora":"14:02",
    "destino":"Múnich",
    "duracion":90
  },
  {
    "compania":"Finnair",
    "hora":"09:19",
    "destino":"Madrid",
    "duracion":432
  },
  {
    "compania":"Air France",
    "hora":"13:36",
    "destino":"Ginebra",
    "duracion":314
  },
  {
    "compania":"Alitalia",
    "hora":"07:04",
    "destino":"Nueva York",
    "duracion":421
  },
  {
    "compania":"EasyJet",
    "hora":"14:12",
    "destino":"Sevilla",
    "duracion":572
  },
  {
    "compania":"Swiss",
    "hora":"12:34",
    "destino":"París",
    "duracion":433
  },
  {
    "compania":"EasyJet",
    "hora":"14:48",
    "destino":"Tenerife",
    "duracion":280
  },
  {
    "compania":"Qatar Airways",
    "hora":"14:27",
    "destino":"Marsella",
    "duracion":358
  },
  {
    "compania":"Delta Airlines",
    "hora":"11:10",
    "destino":"Ginebra",
    "duracion":472
  },
  {
    "compania":"Ryanair",
    "hora":"07:46",
    "destino":"Palma",
    "duracion":64
  },
  {
    "compania":"Finnair",
    "hora":"15:53",
    "destino":"Praga",
    "duracion":224
  },
  {
    "compania":"American Airlines",
    "hora":"10:55",
    "destino":"Málaga",
    "duracion":97
  },
  {
    "compania":"Air France",
    "hora":"08:25",
    "destino":"Gran Canaria",
    "duracion":315
  },
  {
    "compania":"Air France",
    "hora":"13:54",
    "destino":"Toronto",
    "duracion":240
  },
  {
    "compania":"Ryanair",
    "hora":"08:43",
    "destino":"Palma",
    "duracion":516
  },
  {
    "compania":"Alitalia",
    "hora":"13:43",
    "destino":"Bruselas",
    "duracion":261
  },
  {
    "compania":"Ryanair",
    "hora":"07:16",
    "destino":"Nueva York",
    "duracion":374
  },
  {
    "compania":"Air France",
    "hora":"12:37",
    "destino":"Zúrich",
    "duracion":117
  },
  {
    "compania":"KLM",
    "hora":"06:53",
    "destino":"Tenerife",
    "duracion":205
  },
  {
    "compania":"Ryanair",
    "hora":"13:06",
    "destino":"Ámsterdam",
    "duracion":454
  },
  {
    "compania":"Ryanair",
    "hora":"09:56",
    "destino":"Bruselas",
    "duracion":471
  },
  {
    "compania":"Emirates",
    "hora":"14:08",
    "destino":"Santiago",
    "duracion":512
  },
  {
    "compania":"TAP",
    "hora":"14:57",
    "destino":"Milán",
    "duracion":86
  },
  {
    "compania":"Vueling",
    "hora":"15:07",
    "destino":"Nueva York",
    "duracion":153
  },
  {
    "compania":"Vueling",
    "hora":"11:43",
    "destino":"Bilbao",
    "duracion":331
  },
  {
    "compania":"Lufthansa",
    "hora":"10:56",
    "destino":"Zúrich",
    "duracion":458
  },
  {
    "compania":"United Airlines",
    "hora":"11:31",
    "destino":"Bruselas",
    "duracion":73
  },
  {
    "compania":"Lufthansa",
    "hora":"06:44",
    "destino":"Ámsterdam",
    "duracion":411
  },
  {
    "compania":"United Airlines",
    "hora":"06:39",
    "destino":"Toronto",
    "duracion":530
  },
  {
    "compania":"Emirates",
    "hora":"06:19",
    "destino":"Valencia",
    "duracion":352
  },
  {
    "compania":"Vueling",
    "hora":"10:23",
    "destino":"Viena",
    "duracion":68
  },
  {
    "compania":"Norwegian",
    "hora":"10:40",
    "destino":"Oslo",
    "duracion":338
  },
  {
    "compania":"American Airlines",
    "hora":"06:55",
    "destino":"Valencia",
    "duracion":468
  },
  {
    "compania":"Lufthansa",
    "hora":"09:39",
    "destino":"Múnich",
    "duracion":210
  },
  {
    "compania":"Norwegian",
    "hora":"07:25",
    "destino":"Valencia",
    "duracion":374
  },
  {
    "compania":"British Airways",
    "hora":"08:20",
    "destino":"Málaga",
    "duracion":167
  },
  {
    "compania":"Turkish Airlines",
    "hora":"11:01",
    "destino":"Chicago",
    "duracion":196
  },
  {
    "compania":"TAP",
    "hora":"13:09",
    "destino":"Ámsterdam",
    "duracion":343
  },
  {
    "compania":"Qatar Airways",
    "hora":"08:06",
    "destino":"Bilbao",
    "duracion":119
  },
  {
    "compania":"Qatar Airways",
    "hora":"13:03",
    "destino":"Estocolmo",
    "duracion":182
  },
  {
    "compania":"Air France",
    "hora":"11:33",
    "destino":"Nueva York",
    "duracion":346
  },
  {
    "compania":"EasyJet",
    "hora":"14:48",
    "destino":"Praga",
    "duracion":446
  },
  {
    "compania":"KLM",
    "hora":"08:11",
    "destino":"Dublín",
    "duracion":466
  },
  {
    "compania":"Turkish Airlines",
    "hora":"15:27",
    "destino":"Nueva York",
    "duracion":343
  },
  {
    "compania":"TAP",
    "hora":"06:57",
    "destino":"Múnich",
    "duracion":141
  },
  {
    "compania":"Vueling",
    "hora":"14:05",
    "destino":"Gran Canaria",
    "duracion":511
  },
  {
    "compania":"Iberia",
    "hora":"07:41",
    "destino":"Ámsterdam",
    "duracion":349
  },
  {
    "compania":"Emirates",
    "hora":"06:31",
    "destino":"Copenhague",
    "duracion":430
  },
  {
    "compania":"Iberia",
    "hora":"08:13",
    "destino":"Marsella",
    "duracion":316
  },
  {
    "compania":"British Airways",
    "hora":"10:47",
    "destino":"Nueva York",
    "duracion":283
  },
  {
    "compania":"TAP",
    "hora":"12:01",
    "destino":"Múnich",
    "duracion":571
  },
  {
    "compania":"Lufthansa",
    "hora":"09:57",
    "destino":"Viena",
    "duracion":61
  },
  {
    "compania":"Air France",
    "hora":"06:20",
    "destino":"Tokio",
    "duracion":446
  },
  {
    "compania":"Vueling",
    "hora":"13:24",
    "destino":"Estocolmo",
    "duracion":120
  },
  {
    "compania":"Vueling",
    "hora":"09:24",
    "destino":"Milán",
    "duracion":300
  },
  {
    "compania":"British Airways",
    "hora":"09:16",
    "destino":"París",
    "duracion":146
  },
  {
    "compania":"Norwegian",
    "hora":"09:05",
    "destino":"Bilbao",
    "duracion":475
  },
  {
    "compania":"Turkish Airlines",
    "hora":"11:20",
    "destino":"Nueva York",
    "duracion":312
  },
  {
    "compania":"Iberia",
    "hora":"06:42",
    "destino":"Toronto",
    "duracion":422
  },
  {
    "compania":"Swiss",
    "hora":"12:30",
    "destino":"Varsovia",
    "duracion":128
  },
  {
    "compania":"Ryanair",
    "hora":"06:42",
    "destino":"Bilbao",
    "duracion":499
  },
  {
    "compania":"Swiss",
    "hora":"07:08",
    "destino":"Ámsterdam",
    "duracion":177
  },
  {
    "compania":"United Airlines",
    "hora":"13:57",
    "destino":"Dubai",
    "duracion":600
  },
  {
    "compania":"Lufthansa",
    "hora":"15:48",
    "destino":"Palma",
    "duracion":282
  },
  {
    "compania":"Qatar Airways",
    "hora":"11:25",
    "destino":"Estocolmo",
    "duracion":536
  },
  {
    "compania":"Iberia",
    "hora":"15:03",
    "destino":"Viena",
    "duracion":559
  },
  {
    "compania":"Ryanair",
    "hora":"15:14",
    "destino":"Varsovia",
    "duracion":215
  },
  {
    "compania":"Ryanair",
    "hora":"08:26",
    "destino":"Toronto",
    "duracion":574
  },
  {
    "compania":"Emirates",
    "hora":"08:21",
    "destino":"Praga",
    "duracion":158
  },
  {
    "compania":"Delta Airlines",
    "hora":"08:39",
    "destino":"Copenhague",
    "duracion":527
  },
  {
    "compania":"Alitalia",
    "hora":"13:12",
    "destino":"Budapest",
    "duracion":154
  },
  {
    "compania":"Finnair",
    "hora":"09:53",
    "destino":"Bruselas",
    "duracion":349
  },
  {
    "compania":"Vueling",
    "hora":"14:32",
    "destino":"Bilbao",
    "duracion":458
  },
  {
    "compania":"KLM",
    "hora":"09:38",
    "destino":"Dubai",
    "duracion":547
  },
  {
    "compania":"Norwegian",
    "hora":"11:44",
    "destino":"Tenerife",
    "duracion":89
  },
  {
    "compania":"EasyJet",
    "hora":"15:35",
    "destino":"Valencia",
    "duracion":314
  },
  {
    "compania":"United Airlines",
    "hora":"06:57",
    "destino":"Budapest",
    "duracion":474
  },
  {
    "compania":"Air France",
    "hora":"11:02",
    "destino":"Valencia",
    "duracion":294
  },
  {
    "compania":"British Airways",
    "hora":"12:57",
    "destino":"Tenerife",
    "duracion":561
  },
  {
    "compania":"Norwegian",
    "hora":"15:19",
    "destino":"Bogotá",
    "duracion":485
  },
  {
    "compania":"Emirates",
    "hora":"09:35",
    "destino":"Zúrich",
    "duracion":86
  },
  {
    "compania":"Emirates",
    "hora":"09:30",
    "destino":"Lisboa",
    "duracion":331
  },
  {
    "compania":"Lufthansa",
    "hora":"07:51",
    "destino":"Dubai",
    "duracion":350
  },
  {
    "compania":"Finnair",
    "hora":"11:33",
    "destino":"Chicago",
    "duracion":336
  },
  {
    "compania":"American Airlines",
    "hora":"11:32",
    "destino":"Valencia",
    "duracion":114
  },
  {
    "compania":"Finnair",
    "hora":"15:27",
    "destino":"Tenerife",
    "duracion":408
  },
  {
    "compania":"Turkish Airlines",
    "hora":"15:05",
    "destino":"Praga",
    "duracion":99
  },
  {
    "compania":"Air France",
    "hora":"15:27",
    "destino":"Chicago",
    "duracion":205
  },
  {
    "compania":"Lufthansa",
    "hora":"15:37",
    "destino":"Doha",
    "duracion":259
  },
  {
    "compania":"Iberia",
    "hora":"12:54",
    "destino":"Frankfurt",
    "duracion":452
  },
  {
    "compania":"Norwegian",
    "hora":"12:26",
    "destino":"Nápoles",
    "duracion":504
  },
  {
    "compania":"British Airways",
    "hora":"10:42",
    "destino":"Roma",
    "duracion":500
  },
  {
    "compania":"British Airways",
    "hora":"09:53",
    "destino":"Toronto",
    "duracion":262
  },
  {
    "compania":"Turkish Airlines",
    "hora":"15:08",
    "destino":"Milán",
    "duracion":199
  },
  {
    "compania":"Alitalia",
    "hora":"14:10",
    "destino":"Copenhague",
    "duracion":405
  },
  {
    "compania":"Finnair",
    "hora":"07:47",
    "destino":"Estocolmo",
    "duracion":526
  },
  {
    "compania":"Lufthansa",
    "hora":"11:52",
    "destino":"Frankfurt",
    "duracion":179
  },
  {
    "compania":"Swiss",
    "hora":"06:32",
    "destino":"Praga",
    "duracion":90
  },
  {
    "compania":"United Airlines",
    "hora":"06:24",
    "destino":"Toronto",
    "duracion":244
  },
  {
    "compania":"Turkish Airlines",
    "hora":"12:18",
    "destino":"Chicago",
    "duracion":409
  },
  {
    "compania":"Norwegian",
    "hora":"07:59",
    "destino":"Nueva York",
    "duracion":424
  },
  {
    "compania":"Finnair",
    "hora":"09:40",
    "destino":"Doha",
    "duracion":564
  },
  {
    "compania":"United Airlines",
    "hora":"06:00",
    "destino":"Marsella",
    "duracion":400
  },
  {
    "compania":"Iberia",
    "hora":"10:27",
    "destino":"Milán",
    "duracion":511
  },
  {
    "compania":"Norwegian",
    "hora":"10:01",
    "destino":"Gran Canaria",
    "duracion":272
  },
  {
    "compania":"British Airways",
    "hora":"11:42",
    "destino":"Estocolmo",
    "duracion":519
  },
  {
    "compania":"Swiss",
    "hora":"13:33",
    "destino":"Viena",
    "duracion":550
  },
  {
    "compania":"Qatar Airways",
    "hora":"14:19",
    "destino":"Estocolmo",
    "duracion":444
  },
  {
    "compania":"Alitalia",
    "hora":"14:12",
    "destino":"Nueva York",
    "duracion":296
  },
  {
    "compania":"Emirates",
    "hora":"12:44",
    "destino":"Ámsterdam",
    "duracion":375
  },
  {
    "compania":"Vueling",
    "hora":"06:37",
    "destino":"Tenerife",
    "duracion":243
  },
  {
    "compania":"Turkish Airlines",
    "hora":"15:52",
    "destino":"Budapest",
    "duracion":207
  },
  {
    "compania":"Swiss",
    "hora":"13:08",
    "destino":"Bilbao",
    "duracion":369
  },
  {
    "compania":"Qatar Airways",
    "hora":"08:34",
    "destino":"Budapest",
    "duracion":429
  },
  {
    "compania":"Iberia",
    "hora":"14:12",
    "destino":"Milán",
    "duracion":148
  },
  {
    "compania":"Air France",
    "hora":"11:47",
    "destino":"Toronto",
    "duracion":164
  },
  {
    "compania":"Emirates",
    "hora":"14:23",
    "destino":"Lisboa",
    "duracion":265
  },
  {
    "compania":"Turkish Airlines",
    "hora":"13:28",
    "destino":"París",
    "duracion":383
  },
  {
    "compania":"Iberia",
    "hora":"15:30",
    "destino":"Bruselas",
    "duracion":291
  },
  {
    "compania":"Lufthansa",
    "hora":"11:32",
    "destino":"Doha",
    "duracion":507
  },
  {
    "compania":"Norwegian",
    "hora":"14:17",
    "destino":"Zúrich",
    "duracion":423
  },
  {
    "compania":"Finnair",
    "hora":"06:09",
    "destino":"Lisboa",
    "duracion":354
  },
  {
    "compania":"TAP",
    "hora":"10:21",
    "destino":"Valencia",
    "duracion":295
  },
  {
    "compania":"Alitalia",
    "hora":"12:53",
    "destino":"Roma",
    "duracion":429
  },
  {
    "compania":"Qatar Airways",
    "hora":"13:30",
    "destino":"Milán",
    "duracion":143
  },
  {
    "compania":"Ryanair",
    "hora":"08:14",
    "destino":"Valencia",
    "duracion":378
  },
  {
    "compania":"Swiss",
    "hora":"09:50",
    "destino":"Marsella",
    "duracion":545
  },
  {
    "compania":"Emirates",
    "hora":"11:01",
    "destino":"Nápoles",
    "duracion":114
  },
  {
    "compania":"Swiss",
    "hora":"08:03",
    "destino":"París",
    "duracion":315
  },
  {
    "compania":"Emirates",
    "hora":"11:41",
    "destino":"Estocolmo",
    "duracion":385
  },
  {
    "compania":"Vueling",
    "hora":"07:41",
    "destino":"Tenerife",
    "duracion":442
  },
  {
    "compania":"Iberia",
    "hora":"15:25",
    "destino":"Oslo",
    "duracion":442
  },
  {
    "compania":"American Airlines",
    "hora":"07:30",
    "destino":"Oslo",
    "duracion":387
  },
  {
    "compania":"Swiss",
    "hora":"11:18",
    "destino":"Ginebra",
    "duracion":533
  },
  {
    "compania":"Air France",
    "hora":"10:15",
    "destino":"Múnich",
    "duracion":143
  },
  {
    "compania":"American Airlines",
    "hora":"15:59",
    "destino":"Múnich",
    "duracion":151
  },
  {
    "compania":"United Airlines",
    "hora":"14:58",
    "destino":"Madrid",
    "duracion":167
  },
  {
    "compania":"Emirates",
    "hora":"09:39",
    "destino":"Nápoles",
    "duracion":479
  },
  {
    "compania":"Swiss",
    "hora":"13:34",
    "destino":"Oslo",
    "duracion":440
  },
  {
    "compania":"KLM",
    "hora":"13:41",
    "destino":"Madrid",
    "duracion":359
  },
  {
    "compania":"TAP",
    "hora":"08:36",
    "destino":"Milán",
    "duracion":78
  },
  {
    "compania":"Finnair",
    "hora":"09:16",
    "destino":"Dublín",
    "duracion":222
  },
  {
    "compania":"Iberia",
    "hora":"07:05",
    "destino":"Palma",
    "duracion":366
  },
  {
    "compania":"Iberia",
    "hora":"09:53",
    "destino":"Dublín",
    "duracion":316
  },
  {
    "compania":"American Airlines",
    "hora":"11:39",
    "destino":"Dubai",
    "duracion":216
  },
  {
    "compania":"Alitalia",
    "hora":"10:41",
    "destino":"Marsella",
    "duracion":134
  },
  {
    "compania":"Swiss",
    "hora":"06:11",
    "destino":"Múnich",
    "duracion":323
  },
  {
    "compania":"Swiss",
    "hora":"15:59",
    "destino":"Málaga",
    "duracion":119
  },
  {
    "compania":"Emirates",
    "hora":"12:26",
    "destino":"Frankfurt",
    "duracion":325
  },
  {
    "compania":"Iberia",
    "hora":"12:19",
    "destino":"Lisboa",
    "duracion":365
  },
  {
    "compania":"Alitalia",
    "hora":"14:12",
    "destino":"Toronto",
    "duracion":194
  },
  {
    "compania":"Ryanair",
    "hora":"08:12",
    "destino":"Tokio",
    "duracion":566
  },
  {
    "compania":"EasyJet",
    "hora":"11:19",
    "destino":"Praga",
    "duracion":494
  },
  {
    "compania":"Swiss",
    "hora":"07:45",
    "destino":"Frankfurt",
    "duracion":591
  },
  {
    "compania":"TAP",
    "hora":"07:12",
    "destino":"Estocolmo",
    "duracion":337
  },
  {
    "compania":"Delta Airlines",
    "hora":"15:30",
    "destino":"Varsovia",
    "duracion":300
  },
  {
    "compania":"EasyJet",
    "hora":"13:31",
    "destino":"Valencia",
    "duracion":170
  },
  {
    "compania":"Emirates",
    "hora":"08:39",
    "destino":"Londres",
    "duracion":550
  },
  {
    "compania":"Lufthansa",
    "hora":"08:15",
    "destino":"Nueva York",
    "duracion":246
  },
  {
    "compania":"EasyJet",
    "hora":"11:14",
    "destino":"Buenos Aires",
    "duracion":497
  },
  {
    "compania":"Turkish Airlines",
    "hora":"07:40",
    "destino":"Varsovia",
    "duracion":374
  },
  {
    "compania":"Delta Airlines",
    "hora":"08:48",
    "destino":"Dublín",
    "duracion":173
  },
  {
    "compania":"United Airlines",
    "hora":"08:46",
    "destino":"Santiago",
    "duracion":220
  },
  {
    "compania":"Air France",
    "hora":"12:23",
    "destino":"Múnich",
    "duracion":525
  },
  {
    "compania":"Norwegian",
    "hora":"12:41",
    "destino":"Roma",
    "duracion":276
  },
  {
    "compania":"Turkish Airlines",
    "hora":"13:42",
    "destino":"Valencia",
    "duracion":86
  },
  {
    "compania":"Emirates",
    "hora":"11:50",
    "destino":"Lyon",
    "duracion":172
  },
  {
    "compania":"United Airlines",
    "hora":"11:43",
    "destino":"Tenerife",
    "duracion":75
  },
  {
    "compania":"KLM",
    "hora":"09:06",
    "destino":"Dubai",
    "duracion":466
  },
  {
    "compania":"Delta Airlines",
    "hora":"08:01",
    "destino":"Varsovia",
    "duracion":463
  },
  {
    "compania":"Finnair",
    "hora":"13:04",
    "destino":"Tokio",
    "duracion":280
  },
  {
    "compania":"Swiss",
    "hora":"06:07",
    "destino":"Frankfurt",
    "duracion":449
  },
  {
    "compania":"Emirates",
    "hora":"12:34",
    "destino":"Nueva York",
    "duracion":216
  },
  {
    "compania":"Delta Airlines",
    "hora":"06:12",
    "destino":"Palma",
    "duracion":233
  },
  {
    "compania":"United Airlines",
    "hora":"15:57",
    "destino":"Bruselas",
    "duracion":100
  },
  {
    "compania":"Qatar Airways",
    "hora":"14:13",
    "destino":"Doha",
    "duracion":522
  },
  {
    "compania":"Norwegian",
    "hora":"08:00",
    "destino":"Marsella",
    "duracion":119
  },
  {
    "compania":"Turkish Airlines",
    "hora":"11:42",
    "destino":"Zúrich",
    "duracion":558
  },
  {
    "compania":"British Airways",
    "hora":"07:47",
    "destino":"Dubai",
    "duracion":380
  },
  {
    "compania":"Air France",
    "hora":"11:40",
    "destino":"Toronto",
    "duracion":236
  },
  {
    "compania":"KLM",
    "hora":"14:10",
    "destino":"Bilbao",
    "duracion":128
  },
  {
    "compania":"TAP",
    "hora":"15:01",
    "destino":"Ginebra",
    "duracion":567
  },
  {
    "compania":"EasyJet",
    "hora":"11:20",
    "destino":"Marsella",
    "duracion":288
  },
  {
    "compania":"KLM",
    "hora":"10:25",
    "destino":"Bruselas",
    "duracion":176
  },
  {
    "compania":"TAP",
    "hora":"07:39",
    "destino":"Bruselas",
    "duracion":560
  },
  {
    "compania":"Alitalia",
    "hora":"11:56",
    "destino":"Bogotá",
    "duracion":122
  },
  {
    "compania":"EasyJet",
    "hora":"12:34",
    "destino":"Bogotá",
    "duracion":397
  },
  {
    "compania":"Qatar Airways",
    "hora":"10:54",
    "destino":"Roma",
    "duracion":251
  },
  {
    "compania":"Delta Airlines",
    "hora":"08:54",
    "destino":"Nápoles",
    "duracion":500
  },
  {
    "compania":"Alitalia",
    "hora":"11:52",
    "destino":"Estocolmo",
    "duracion":577
  },
  {
    "compania":"EasyJet",
    "hora":"15:12",
    "destino":"Nueva York",
    "duracion":83
  },
  {
    "compania":"Iberia",
    "hora":"10:18",
    "destino":"Viena",
    "duracion":529
  },
  {
    "compania":"United Airlines",
    "hora":"14:17",
    "destino":"Estocolmo",
    "duracion":291
  },
  {
    "compania":"Alitalia",
    "hora":"10:09",
    "destino":"Valencia",
    "duracion":553
  },
  {
    "compania":"Air France",
    "hora":"11:37",
    "destino":"Nápoles",
    "duracion":266
  },
  {
    "compania":"Iberia",
    "hora":"07:35",
    "destino":"Nápoles",
    "duracion":546
  }
];