export const peliculas = [
  "Indiana Jones",
  "Zootopia",
  "The Godfather",
  "Citizen Kane",
  "Schindler's List",
  "The Godfather: Part II",
  "Pulp Fiction",
  "The Good, the Bad and the Ugly",
  "12 Angry Men",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Forrest Gump",
  "The Silence of the Lambs",
  "Casablanca",
  "A Clockwork Orange",
  "The Shining",
  "Apocalypse Now",
  "City of God",
  "Seven Samurai",
  "Star Wars: Episode IV - A New Hope",
  "Back to the Future",
  "The Matrix",
  "American History X",
  "Fight Club",
  "Gladiator",
  "Taxi Driver",
  "Life Is Beautiful"
];